site_name: logagent-js
repo_url: https://github.com/sematext/logagent-js
theme: readthedocs
pages:
- Features and Overview: index.md
- Installation: installation.md
- Command Line Options: cli-parameters.md
- Log Parser and pattern definitions: parser.md
- Node.js API: nodejs-api.md

