input: 
  stdin: true 

output: 
  sematext-spm:
    module: output-influxdb
    url: http://127.0.0.1:8086
    db: sensor_data
    # flush interval in seconds
    flushInterval: 5
    debug: true
    # following message fields are not used  
    # as tags or fields influxDB output
    ignoreFields: 
      - logSource
      - message
    # optional filter settings matching data field with regular expressions
    filter: 
      field: logSource
      match: .*
