# Global options
options:
  includeOriginalLine: false
input:
  kafka: 
    module: input-kafka
    kafkaHost: localhost:9092
    groupId: ExampleTestGroup
    topic: test
    sslEnable: true
    sessionTimeout: 15000
    

output:
  stdout: yaml # use 'pretty' for pretty json and 'ldjson' for line delimited json (default)
  