# Global options
options:
  includeOriginalLine: false
input:
  kafka: 
    module: input-kafka
    kafkaHost: localhost:9092
    groupId: ExampleTestGroup
    topic: test
    ssl: false
    sessionTimeout: 15000
    

output:
  # print parsed logs in YAML format to stdout if supress is set false    
  stdout: yaml # use 'pretty' for pretty json and 'ldjson' for line delimited json (default)
  