input:
  mysql-json:
    module: mysql-query
    server: 
      host: 'localhost'
      user: 'root'
      password: ''
      database: 'test'
    queries: 
      - sourceName: query1
        sql: SELECT * FROM potluck where signup_date < '$queryTime'
      - sourceName: query2      
        sql: SELECT * FROM potluck where name = 'Tina' and signup_date < '$queryTime'
      - sourceName: query3
        sql: SELECT * FROM potluck where name = 'Sandy' and signup_date < '$queryTime'
    interval: 1
    debug: true

output:
    stdout: yaml
