input:
  mysql-json:
    module: mysql-query
    server: 
      host: 'localhost'
      user: 'root'
      password: ''
      database: 'test'
    sql: SELECT * FROM potluck where signup_date < '$queryTime'
    sourceName: MYSQL
    interval: 1
    debug: true

output:
    stdout: yaml
