input:
  mysql-json:
    module: mysql-query
    server: 
      host: 'localhost'
      user: 'root'
      password: ''
      database: 'test'
    sql: 'SELECT * FROM potluck'
    sourceName: MYSQL
    interval: 0.0000001

output:
    stdout: yaml