# Global options
options:
  # Enable/disable GeoIP lookups
  # Startup of logagent might be slower, when downloading the GeoIP database
  geoipEnabled: true

outputFilter:
  - module: access-watch
    config:
      apiKey: c8dc2cbd26df71dbe92cb4048bd28f84

output:
  stdout: yaml
