input: 
  stdin: true 

# example parser, extracting country name to route file output to country files named {country}.json
parser:
  patternFiles: []
  patterns:
    - sourceName: !!js/regexp /.*/
      match:
        - type: countryInfo
          regex: !!js/regexp /(.+?)\s(.+?)\s(.+?)/i
          fields: 
            - country:string
            - anotherField:string
            - andAnotherField:string

output:
  files:
    module: output-files
    fileName: '/tmp/{country}.json'
    # available format values: 'ldjson' (default), 'yaml', 'pretty' (pretty JSON)
    format: ldjson
    # matches context.sourceName == data.logSource
    sourceName: .*
    # matches data._type field 
    typeName: countryInfo
    # properties for https://www.npmjs.com/search?q=rotating-file-stream
    size: 10M
    maxFiles: 2
    interval: 1d
    compress: true
