# Global options
options:
  # Enable/disable GeoIP lookups
  # Startup of logagent might be slower, when downloading the GeoIP database
  geoipEnabled: true

outputFilter:
  - module: access-watch
    config:
      # Get a free Reveal API Key from Access Watch:
      # https://access.watch/reveal
      # Basic configuration instructions for Logagent:
      # https://access.watch/reveal/logagent
      # apiKey: YOUR_REVEAL_API_KEY_HERE

output:
  stdout: yaml
